### 1D numpy array to a pandas dataframe

In [1]:
import os
import numpy as np
import pandas as pd

In [4]:
arr = np.array([10, 20, 30, 40, 50])
# convert to pandas dataframe
df = pd.DataFrame(arr)
df

0
0  10
1  20
2  30
3  40
4  50

In [5]:
print(arr)

[10 20 30 40 50]


### 2D numpy array to a pandas dataframe

In [7]:
import os
import numpy as np
import pandas as pd

In [8]:
arr2 = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
# convert to pandas dataframe
df2 = pd.DataFrame(arr2)
df2

0   1   2   3    4
0  10  20  30  40   50
1  60  70  80  90  100

In [9]:
print(arr2)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


### Another 2D numpy array to a pandas dataframe

In [10]:
arr3 = np.array([['English', 'Math', 'Science', 'Economics', 'Literature'], [60, 70, 80, 90, 100]])
# convert to pandas dataframe
df3 = pd.DataFrame(arr3)
df3

0     1        2          3           4
0  English  Math  Science  Economics  Literature
1       60    70       80         90         100

In [11]:
print(arr3)

[['English' 'Math' 'Science' 'Economics' 'Literature']
 ['60' '70' '80' '90' '100']]
